In [1]:
#library(alr3)
#library(car)
library(carData)
library(model)

In [2]:
X<-matrix(c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.3,1.3,2,2,2.7,3.3,3.3,3.7,3.7,4,4,4,4.7,4.7,5,5.3,5.3,5.3,5.7,6,6,6.3,6.7), nrow = 23)

In [3]:
X

[,1] [,2]
 [1,] 1    1.3 
 [2,] 1    1.3 
 [3,] 1    2.0 
 [4,] 1    2.0 
 [5,] 1    2.7 
 [6,] 1    3.3 
 [7,] 1    3.3 
 [8,] 1    3.7 
 [9,] 1    3.7 
[10,] 1    4.0 
[11,] 1    4.0 
[12,] 1    4.0 
[13,] 1    4.7 
[14,] 1    4.7 
[15,] 1    5.0 
[16,] 1    5.3 
[17,] 1    5.3 
[18,] 1    5.3 
[19,] 1    5.7 
[20,] 1    6.0 
[21,] 1    6.0 
[22,] 1    6.3 
[23,] 1    6.7

In [4]:
U<-matrix(c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24), nrow = 23)

In [5]:
W<-matrix(c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.96), nrow = 23)

In [6]:
I=diag(1,nrow=23)

In [7]:
I

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,] 0    1    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0    
 [4,] 0    0    0    1    0    0    0    0    0    0     ⋯     0     0    
 [5,] 0    0    0    0    1    0    0    0    0    0     ⋯     0     0    
 [6,] 0    0    0    0    0    1    0    0    0    0     ⋯     0     0    
 [7,] 0    0    0    0    0    0    1    0    0    0     ⋯     0     0    
 [8,] 0    0    0    0    0    0    0    1    0    0     ⋯     0     0    
 [9,] 0    0    0    0    0    0    0    0    1    0     ⋯     0     0    
[10,] 0    0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     ⋯     1     0    
[15,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     1    
[16,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[22,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[23,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0     0    
 [2,] 0     0     0     0     0     0     0     0    
 [3,] 0     0     0     0     0     0     0     0    
 [4,] 0     0     0     0     0     0     0     0    
 [5,] 0     0     0     0     0     0     0     0    
 [6,] 0     0     0     0     0     0     0     0    
 [7,] 0     0     0     0     0     0     0     0    
 [8,] 0     0     0     0     0     0     0     0    
 [9,] 0     0     0     0     0     0     0     0    
[10,] 0     0     0     0     0     0     0     0    
[11,] 0     0     0     0     0     0     0     0    
[12,] 0     0     0     0     0     0     0     0    
[13,] 0     0     0     0     0     0     0     0    
[14,] 0     0     0     0     0     0     0     0    
[15,] 0     0     0     0     0     0     0     0    
[16,] 1     0     0     0     0     0     0     0    
[17,] 0     1     0     0     0     0     0     0    
[18,] 0     0     1     0     0     0     0     0    
[19,] 0     0     0     1     0     0     0     0    
[20,] 0     0     0     0     1     0     0     0    
[21,] 0     0     0     0     0     1     0     0    
[22,] 0     0     0     0     0     0     1     0    
[23,] 0     0     0     0     0     0     0     1

In [8]:
V=I+U

In [9]:
Vi=I-W

In [10]:
Y<-matrix(c(2.3,1.8,2.8,1.5,2.2,3.8,1.8,3.7,1.7,2.8,2.8,2.2,3.2,1.9,1.8,3.5,2.8,2.1,3.4,3.2,3,3,5.9), nrow = 23)

In [11]:
Vi

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,] 0    1    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0    
 [4,] 0    0    0    1    0    0    0    0    0    0     ⋯     0     0    
 [5,] 0    0    0    0    1    0    0    0    0    0     ⋯     0     0    
 [6,] 0    0    0    0    0    1    0    0    0    0     ⋯     0     0    
 [7,] 0    0    0    0    0    0    1    0    0    0     ⋯     0     0    
 [8,] 0    0    0    0    0    0    0    1    0    0     ⋯     0     0    
 [9,] 0    0    0    0    0    0    0    0    1    0     ⋯     0     0    
[10,] 0    0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     ⋯     1     0    
[15,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     1    
[16,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[22,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[23,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0     0.00 
 [2,] 0     0     0     0     0     0     0     0.00 
 [3,] 0     0     0     0     0     0     0     0.00 
 [4,] 0     0     0     0     0     0     0     0.00 
 [5,] 0     0     0     0     0     0     0     0.00 
 [6,] 0     0     0     0     0     0     0     0.00 
 [7,] 0     0     0     0     0     0     0     0.00 
 [8,] 0     0     0     0     0     0     0     0.00 
 [9,] 0     0     0     0     0     0     0     0.00 
[10,] 0     0     0     0     0     0     0     0.00 
[11,] 0     0     0     0     0     0     0     0.00 
[12,] 0     0     0     0     0     0     0     0.00 
[13,] 0     0     0     0     0     0     0     0.00 
[14,] 0     0     0     0     0     0     0     0.00 
[15,] 0     0     0     0     0     0     0     0.00 
[16,] 1     0     0     0     0     0     0     0.00 
[17,] 0     1     0     0     0     0     0     0.00 
[18,] 0     0     1     0     0     0     0     0.00 
[19,] 0     0     0     1     0     0     0     0.00 
[20,] 0     0     0     0     1     0     0     0.00 
[21,] 0     0     0     0     0     1     0     0.00 
[22,] 0     0     0     0     0     0     1     0.00 
[23,] 0     0     0     0     0     0     0     0.04

In [12]:
Xt=t(X)

In [13]:
C=Xt%*%Vi%*%X

In [14]:
J=diag(1,nrow=2)

solve(C,J)

[,1]        [,2]       
[1,]  0.38593389 -0.08352231
[2,] -0.08352231  0.02048373

In [15]:
C1=solve(C,J)

In [16]:
C2=Xt%*%Vi%*%Y

In [17]:
C1

[,1]        [,2]       
[1,]  0.38593389 -0.08352231
[2,] -0.08352231  0.02048373

In [18]:
C1%*%C2

[,1]     
[1,] 1.8188667
[2,] 0.1941534

In [19]:
#H

In [20]:
X1<- c(1.76,1.55,2.73,2.73,2.56,2.8,2.8,1.84,2.16,1.98,0.59,0.8,0.8,1.05,1.8,1.8,1.77,2.3,2.03,1.91,1.91,1.91,0.76,2.13,2.13,1.51,2.05)

In [21]:
X1

[1] 1.76 1.55 2.73 2.73 2.56 2.80 2.80 1.84 2.16 1.98 0.59 0.80 0.80 1.05 1.80
[16] 1.80 1.77 2.30 2.03 1.91 1.91 1.91 0.76 2.13 2.13 1.51 2.05

In [22]:
X2<- c(0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.474,0.474,0.474,0.474,0.474,0.474,0.474,0.474,0.474)

In [23]:
X2

[1] 0.700 0.700 0.700 0.700 0.700 0.700 0.700 0.700 0.700 0.200 0.200 0.200
[13] 0.200 0.200 0.200 0.200 0.200 0.200 0.474 0.474 0.474 0.474 0.474 0.474
[25] 0.474 0.474 0.474

In [24]:
X3<- c(7.8,8.9,8.9,7.2,8.4,8.7,7.4,8.7,8.8,7.6,6.5,6.7,6.2,7,7.3,6.5,7.6,8.2,7.6,8.3,8.2,6.9,7.4,7.6,6.9,7.5,7.6)

In [25]:
X3

[1] 7.8 8.9 8.9 7.2 8.4 8.7 7.4 8.7 8.8 7.6 6.5 6.7 6.2 7.0 7.3 6.5 7.6 8.2 7.6
[20] 8.3 8.2 6.9 7.4 7.6 6.9 7.5 7.6

In [26]:
Yh<- c(110.4,102.8,101,108.4,100.7,100.3,102,93.7,98.9,96.6,99.4,96.2,99,88.4,75.3,92,82.4,77.1,74,65.7,56.8,62.1,61,53.2,59.4,58.7,58)

In [27]:
Yh

[1] 110.4 102.8 101.0 108.4 100.7 100.3 102.0  93.7  98.9  96.6  99.4  96.2
[13]  99.0  88.4  75.3  92.0  82.4  77.1  74.0  65.7  56.8  62.1  61.0  53.2
[25]  59.4  58.7  58.0

In [31]:
lX1=log(X1)
lX2=log(X2)
lX3=log(X3)
lY=log(Yh)

In [37]:
data_H <- data.frame(lX1, lX2, lX3, lY)
data_H

lX1         lX2        lX3      lY      
1   0.56531381 -0.3566749 2.054124 4.704110
2   0.43825493 -0.3566749 2.186051 4.632785
3   1.00430161 -0.3566749 2.186051 4.615121
4   1.00430161 -0.3566749 1.974081 4.685828
5   0.94000726 -0.3566749 2.128232 4.612146
6   1.02961942 -0.3566749 2.163323 4.608166
7   1.02961942 -0.3566749 2.001480 4.624973
8   0.60976557 -0.3566749 2.163323 4.540098
9   0.77010822 -0.3566749 2.174752 4.594109
10  0.68309684 -1.6094379 2.028148 4.570579
11 -0.52763274 -1.6094379 1.871802 4.599152
12 -0.22314355 -1.6094379 1.902108 4.566429
13 -0.22314355 -1.6094379 1.824549 4.595120
14  0.04879016 -1.6094379 1.945910 4.481872
15  0.58778666 -1.6094379 1.987874 4.321480
16  0.58778666 -1.6094379 1.871802 4.521789
17  0.57097955 -1.6094379 2.028148 4.411585
18  0.83290912 -1.6094379 2.104134 4.345103
19  0.70803579 -0.7465480 2.028148 4.304065
20  0.64710324 -0.7465480 2.116256 4.185099
21  0.64710324 -0.7465480 2.104134 4.039536
22  0.64710324 -0.7465480 1.931521 4.128746
23 -0.27443685 -0.7465480 2.001480 4.110874
24  0.75612198 -0.7465480 2.028148 3.974058
25  0.75612198 -0.7465480 1.931521 4.084294
26  0.41210965 -0.7465480 2.014903 4.072440
27  0.71783979 -0.7465480 2.028148 4.060443

In [38]:
regresion_H <- lm(lY ~ lX1+lX2+lX3, data_H)
summary(regresion_H)


Call:
lm(formula = lY ~ lX1 + lX2 + lX3, data = data_H)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.42296 -0.24323  0.09512  0.17989  0.31946 

Coefficients:
             Estimate Std. Error t value Pr(>|t|)  
(Intercept)  3.757191   1.376425   2.730   0.0119 *
lX1         -0.041636   0.148753  -0.280   0.7821  
lX2         -0.006541   0.124674  -0.052   0.9586  
lX3          0.328588   0.662088   0.496   0.6244  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.2522 on 23 degrees of freedom
Multiple R-squared:  0.01231,	Adjusted R-squared:  -0.1165 
F-statistic: 0.09556 on 3 and 23 DF,  p-value: 0.9617


In [39]:
coef(`regresion_H`)

(Intercept)          lX1          lX2          lX3 
 3.757190935 -0.041636470 -0.006541014  0.328588303

In [40]:
data_H1 <- data.frame(X1, X2, X3, Yh)
data_H1

X1   X2    X3  Yh   
1  1.76 0.700 7.8 110.4
2  1.55 0.700 8.9 102.8
3  2.73 0.700 8.9 101.0
4  2.73 0.700 7.2 108.4
5  2.56 0.700 8.4 100.7
6  2.80 0.700 8.7 100.3
7  2.80 0.700 7.4 102.0
8  1.84 0.700 8.7  93.7
9  2.16 0.700 8.8  98.9
10 1.98 0.200 7.6  96.6
11 0.59 0.200 6.5  99.4
12 0.80 0.200 6.7  96.2
13 0.80 0.200 6.2  99.0
14 1.05 0.200 7.0  88.4
15 1.80 0.200 7.3  75.3
16 1.80 0.200 6.5  92.0
17 1.77 0.200 7.6  82.4
18 2.30 0.200 8.2  77.1
19 2.03 0.474 7.6  74.0
20 1.91 0.474 8.3  65.7
21 1.91 0.474 8.2  56.8
22 1.91 0.474 6.9  62.1
23 0.76 0.474 7.4  61.0
24 2.13 0.474 7.6  53.2
25 2.13 0.474 6.9  59.4
26 1.51 0.474 7.5  58.7
27 2.05 0.474 7.6  58.0

In [41]:
regresion_H.1 <- lm(Yh ~ X1+X2+X3, data_H1)
summary(regresion_H.1)


Call:
lm(formula = Yh ~ X1 + X2 + X3, data = data_H1)

Residuals:
    Min      1Q  Median      3Q     Max 
-31.132 -20.674   9.048  13.237  20.328 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)  
(Intercept)  81.5404    43.0137   1.896   0.0706 .
X1           -1.0976     7.7363  -0.142   0.8884  
X2           24.3501    26.0498   0.935   0.3596  
X3           -0.8438     6.6452  -0.127   0.9001  
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 19.41 on 23 degrees of freedom
Multiple R-squared:  0.05293,	Adjusted R-squared:  -0.0706 
F-statistic: 0.4285 on 3 and 23 DF,  p-value: 0.7345


In [42]:
coef(`regresion_H.1`)

(Intercept)          X1          X2          X3 
 81.5404383  -1.0975545  24.3500825  -0.8437578