In [1]:
#library(alr3)
#library(car)
library(carData)
library(model)

In [2]:
X<-matrix(c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.3,1.3,2,2,2.7,3.3,3.3,3.7,3.7,4,4,4,4.7,4.7,5,5.3,5.3,5.3,5.7,6,6,6.3,6.7), nrow = 23)

In [3]:
X

[,1] [,2]
 [1,] 1    1.3 
 [2,] 1    1.3 
 [3,] 1    2.0 
 [4,] 1    2.0 
 [5,] 1    2.7 
 [6,] 1    3.3 
 [7,] 1    3.3 
 [8,] 1    3.7 
 [9,] 1    3.7 
[10,] 1    4.0 
[11,] 1    4.0 
[12,] 1    4.0 
[13,] 1    4.7 
[14,] 1    4.7 
[15,] 1    5.0 
[16,] 1    5.3 
[17,] 1    5.3 
[18,] 1    5.3 
[19,] 1    5.7 
[20,] 1    6.0 
[21,] 1    6.0 
[22,] 1    6.3 
[23,] 1    6.7

In [4]:
U<-matrix(c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24), nrow = 23)

In [5]:
W<-matrix(c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.96), nrow = 23)

In [6]:
I=diag(1,nrow=23)

In [7]:
I

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,] 0    1    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0    
 [4,] 0    0    0    1    0    0    0    0    0    0     ⋯     0     0    
 [5,] 0    0    0    0    1    0    0    0    0    0     ⋯     0     0    
 [6,] 0    0    0    0    0    1    0    0    0    0     ⋯     0     0    
 [7,] 0    0    0    0    0    0    1    0    0    0     ⋯     0     0    
 [8,] 0    0    0    0    0    0    0    1    0    0     ⋯     0     0    
 [9,] 0    0    0    0    0    0    0    0    1    0     ⋯     0     0    
[10,] 0    0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     ⋯     1     0    
[15,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     1    
[16,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[22,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[23,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0     0    
 [2,] 0     0     0     0     0     0     0     0    
 [3,] 0     0     0     0     0     0     0     0    
 [4,] 0     0     0     0     0     0     0     0    
 [5,] 0     0     0     0     0     0     0     0    
 [6,] 0     0     0     0     0     0     0     0    
 [7,] 0     0     0     0     0     0     0     0    
 [8,] 0     0     0     0     0     0     0     0    
 [9,] 0     0     0     0     0     0     0     0    
[10,] 0     0     0     0     0     0     0     0    
[11,] 0     0     0     0     0     0     0     0    
[12,] 0     0     0     0     0     0     0     0    
[13,] 0     0     0     0     0     0     0     0    
[14,] 0     0     0     0     0     0     0     0    
[15,] 0     0     0     0     0     0     0     0    
[16,] 1     0     0     0     0     0     0     0    
[17,] 0     1     0     0     0     0     0     0    
[18,] 0     0     1     0     0     0     0     0    
[19,] 0     0     0     1     0     0     0     0    
[20,] 0     0     0     0     1     0     0     0    
[21,] 0     0     0     0     0     1     0     0    
[22,] 0     0     0     0     0     0     1     0    
[23,] 0     0     0     0     0     0     0     1

In [8]:
V=I+U

In [9]:
Vi=I-W

In [10]:
Y<-matrix(c(2.3,1.8,2.8,1.5,2.2,3.8,1.8,3.7,1.7,2.8,2.8,2.2,3.2,1.9,1.8,3.5,2.8,2.1,3.4,3.2,3,3,5.9), nrow = 23)

In [11]:
Vi

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,] 0    1    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0    
 [4,] 0    0    0    1    0    0    0    0    0    0     ⋯     0     0    
 [5,] 0    0    0    0    1    0    0    0    0    0     ⋯     0     0    
 [6,] 0    0    0    0    0    1    0    0    0    0     ⋯     0     0    
 [7,] 0    0    0    0    0    0    1    0    0    0     ⋯     0     0    
 [8,] 0    0    0    0    0    0    0    1    0    0     ⋯     0     0    
 [9,] 0    0    0    0    0    0    0    0    1    0     ⋯     0     0    
[10,] 0    0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     ⋯     1     0    
[15,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     1    
[16,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[22,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[23,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0     0.00 
 [2,] 0     0     0     0     0     0     0     0.00 
 [3,] 0     0     0     0     0     0     0     0.00 
 [4,] 0     0     0     0     0     0     0     0.00 
 [5,] 0     0     0     0     0     0     0     0.00 
 [6,] 0     0     0     0     0     0     0     0.00 
 [7,] 0     0     0     0     0     0     0     0.00 
 [8,] 0     0     0     0     0     0     0     0.00 
 [9,] 0     0     0     0     0     0     0     0.00 
[10,] 0     0     0     0     0     0     0     0.00 
[11,] 0     0     0     0     0     0     0     0.00 
[12,] 0     0     0     0     0     0     0     0.00 
[13,] 0     0     0     0     0     0     0     0.00 
[14,] 0     0     0     0     0     0     0     0.00 
[15,] 0     0     0     0     0     0     0     0.00 
[16,] 1     0     0     0     0     0     0     0.00 
[17,] 0     1     0     0     0     0     0     0.00 
[18,] 0     0     1     0     0     0     0     0.00 
[19,] 0     0     0     1     0     0     0     0.00 
[20,] 0     0     0     0     1     0     0     0.00 
[21,] 0     0     0     0     0     1     0     0.00 
[22,] 0     0     0     0     0     0     1     0.00 
[23,] 0     0     0     0     0     0     0     0.04

In [12]:
Xt=t(X)

In [13]:
C=Xt%*%Vi%*%X

In [14]:
J=diag(1,nrow=2)

solve(C,J)

[,1]        [,2]       
[1,]  0.38593389 -0.08352231
[2,] -0.08352231  0.02048373

In [15]:
C1=solve(C,J)

In [16]:
C2=Xt%*%Vi%*%Y

In [17]:
C1

[,1]        [,2]       
[1,]  0.38593389 -0.08352231
[2,] -0.08352231  0.02048373

In [18]:
C1%*%C2

[,1]     
[1,] 1.8188667
[2,] 0.1941534

## H

In [19]:
X1<- c(1.76,1.55,2.73,2.73,2.56,2.8,2.8,1.84,2.16,1.98,0.59,0.8,0.8,1.05,1.8,1.8,1.77,2.3,2.03,1.91,1.91,1.91,0.76,2.13,2.13,1.51,2.05)

In [20]:
X1

[1] 1.76 1.55 2.73 2.73 2.56 2.80 2.80 1.84 2.16 1.98 0.59 0.80 0.80 1.05 1.80
[16] 1.80 1.77 2.30 2.03 1.91 1.91 1.91 0.76 2.13 2.13 1.51 2.05

In [21]:
X2<- c(0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.07,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.02,0.474,0.474,0.474,0.474,0.474,0.474,0.474,0.474,0.474)

In [22]:
X2

[1] 0.070 0.070 0.070 0.070 0.070 0.070 0.070 0.070 0.070 0.020 0.020 0.020
[13] 0.020 0.020 0.020 0.020 0.020 0.020 0.474 0.474 0.474 0.474 0.474 0.474
[25] 0.474 0.474 0.474

In [23]:
X3<- c(7.8,8.9,8.9,7.2,8.4,8.7,7.4,8.7,8.8,7.6,6.5,6.7,6.2,7,7.3,6.5,7.6,8.2,7.6,8.3,8.2,6.9,7.4,7.6,6.9,7.5,7.6)

In [24]:
X3

[1] 7.8 8.9 8.9 7.2 8.4 8.7 7.4 8.7 8.8 7.6 6.5 6.7 6.2 7.0 7.3 6.5 7.6 8.2 7.6
[20] 8.3 8.2 6.9 7.4 7.6 6.9 7.5 7.6

In [25]:
Yh<- c(110.4,102.8,101,108.4,100.7,100.3,102,93.7,98.9,96.6,99.4,96.2,99,88.4,75.3,92,82.4,77.1,74,65.7,56.8,62.1,61,53.2,59.4,58.7,58)

In [26]:
Yh

[1] 110.4 102.8 101.0 108.4 100.7 100.3 102.0  93.7  98.9  96.6  99.4  96.2
[13]  99.0  88.4  75.3  92.0  82.4  77.1  74.0  65.7  56.8  62.1  61.0  53.2
[25]  59.4  58.7  58.0

In [27]:
lX1=log(X1)
lX2=log(X2)
lX3=log(X3)
lY=log(Yh)

In [28]:
data_H <- data.frame(lX1, lX2, lX3, lY)
data_H

lX1         lX2       lX3      lY      
1   0.56531381 -2.659260 2.054124 4.704110
2   0.43825493 -2.659260 2.186051 4.632785
3   1.00430161 -2.659260 2.186051 4.615121
4   1.00430161 -2.659260 1.974081 4.685828
5   0.94000726 -2.659260 2.128232 4.612146
6   1.02961942 -2.659260 2.163323 4.608166
7   1.02961942 -2.659260 2.001480 4.624973
8   0.60976557 -2.659260 2.163323 4.540098
9   0.77010822 -2.659260 2.174752 4.594109
10  0.68309684 -3.912023 2.028148 4.570579
11 -0.52763274 -3.912023 1.871802 4.599152
12 -0.22314355 -3.912023 1.902108 4.566429
13 -0.22314355 -3.912023 1.824549 4.595120
14  0.04879016 -3.912023 1.945910 4.481872
15  0.58778666 -3.912023 1.987874 4.321480
16  0.58778666 -3.912023 1.871802 4.521789
17  0.57097955 -3.912023 2.028148 4.411585
18  0.83290912 -3.912023 2.104134 4.345103
19  0.70803579 -0.746548 2.028148 4.304065
20  0.64710324 -0.746548 2.116256 4.185099
21  0.64710324 -0.746548 2.104134 4.039536
22  0.64710324 -0.746548 1.931521 4.128746
23 -0.27443685 -0.746548 2.001480 4.110874
24  0.75612198 -0.746548 2.028148 3.974058
25  0.75612198 -0.746548 1.931521 4.084294
26  0.41210965 -0.746548 2.014903 4.072440
27  0.71783979 -0.746548 2.028148 4.060443

In [29]:
regresion_H <- lm(lY ~ lX1+lX2+lX3, data_H)
summary(regresion_H)


Call:
lm(formula = lY ~ lX1 + lX2 + lX3, data = data_H)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.32252 -0.07841  0.01167  0.10143  0.25879 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)  3.00845    0.72881   4.128 0.000409 ***
lX1          0.03499    0.09001   0.389 0.701030    
lX2         -0.14425    0.02405  -5.999 4.07e-06 ***
lX3          0.50649    0.36763   1.378 0.181555    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 0.1575 on 23 degrees of freedom
Multiple R-squared:  0.6148,	Adjusted R-squared:  0.5646 
F-statistic: 12.24 on 3 and 23 DF,  p-value: 5.453e-05


In [30]:
coef(`regresion_H`)

(Intercept)         lX1         lX2         lX3 
 3.00844991  0.03499077 -0.14424913  0.50648944

In [31]:
mean(X1)
mean(X2)
mean(X3)
mean(Yh)

[1] 1.857778

[1] 0.188

[1] 7.644444

[1] 84.2037

In [32]:
data_H1 <- data.frame(X1, X2, X3, Yh)
data_H1

X1   X2    X3  Yh   
1  1.76 0.070 7.8 110.4
2  1.55 0.070 8.9 102.8
3  2.73 0.070 8.9 101.0
4  2.73 0.070 7.2 108.4
5  2.56 0.070 8.4 100.7
6  2.80 0.070 8.7 100.3
7  2.80 0.070 7.4 102.0
8  1.84 0.070 8.7  93.7
9  2.16 0.070 8.8  98.9
10 1.98 0.020 7.6  96.6
11 0.59 0.020 6.5  99.4
12 0.80 0.020 6.7  96.2
13 0.80 0.020 6.2  99.0
14 1.05 0.020 7.0  88.4
15 1.80 0.020 7.3  75.3
16 1.80 0.020 6.5  92.0
17 1.77 0.020 7.6  82.4
18 2.30 0.020 8.2  77.1
19 2.03 0.474 7.6  74.0
20 1.91 0.474 8.3  65.7
21 1.91 0.474 8.2  56.8
22 1.91 0.474 6.9  62.1
23 0.76 0.474 7.4  61.0
24 2.13 0.474 7.6  53.2
25 2.13 0.474 6.9  59.4
26 1.51 0.474 7.5  58.7
27 2.05 0.474 7.6  58.0

In [35]:
regresion_H.1 <- lm(Yh ~ X1+X2+X3+X1*X2, data_H1)
summary(regresion_H.1)


Call:
lm(formula = Yh ~ X1 + X2 + X3 + X1 * X2, data = data_H1)

Residuals:
    Min      1Q  Median      3Q     Max 
-22.155  -3.770   1.458   5.503  16.983 

Coefficients:
            Estimate Std. Error t value Pr(>|t|)    
(Intercept)   82.173     20.338   4.040 0.000547 ***
X1             2.463      4.722   0.522 0.607190    
X2           -75.378     39.144  -1.926 0.067168 .  
X3             1.584      3.122   0.507 0.616997    
X1:X2         -1.374     21.265  -0.065 0.949058    
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 10.1 on 22 degrees of freedom
Multiple R-squared:  0.7549,	Adjusted R-squared:  0.7103 
F-statistic: 16.94 on 4 and 22 DF,  p-value: 1.784e-06


In [36]:
coef(`regresion_H.1`)

(Intercept)          X1          X2          X3       X1:X2 
  82.173274    2.462872  -75.378127    1.583885   -1.374159