In [1]:
#library(alr3)
#library(car)
library(carData)
library(model)

In [2]:
X<-matrix(c(1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1.3,1.3,2,2,2.7,3.3,3.3,3.7,3.7,4,4,4,4.7,4.7,5,5.3,5.3,5.3,5.7,6,6,6.3,6.7), nrow = 23)

In [3]:
X

[,1] [,2]
 [1,] 1    1.3 
 [2,] 1    1.3 
 [3,] 1    2.0 
 [4,] 1    2.0 
 [5,] 1    2.7 
 [6,] 1    3.3 
 [7,] 1    3.3 
 [8,] 1    3.7 
 [9,] 1    3.7 
[10,] 1    4.0 
[11,] 1    4.0 
[12,] 1    4.0 
[13,] 1    4.7 
[14,] 1    4.7 
[15,] 1    5.0 
[16,] 1    5.3 
[17,] 1    5.3 
[18,] 1    5.3 
[19,] 1    5.7 
[20,] 1    6.0 
[21,] 1    6.0 
[22,] 1    6.3 
[23,] 1    6.7

In [4]:
U<-matrix(c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,24), nrow = 23)

In [5]:
W<-matrix(c(0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0.96), nrow = 23)

In [6]:
I=diag(1,nrow=23)

In [7]:
I

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,] 0    1    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0    
 [4,] 0    0    0    1    0    0    0    0    0    0     ⋯     0     0    
 [5,] 0    0    0    0    1    0    0    0    0    0     ⋯     0     0    
 [6,] 0    0    0    0    0    1    0    0    0    0     ⋯     0     0    
 [7,] 0    0    0    0    0    0    1    0    0    0     ⋯     0     0    
 [8,] 0    0    0    0    0    0    0    1    0    0     ⋯     0     0    
 [9,] 0    0    0    0    0    0    0    0    1    0     ⋯     0     0    
[10,] 0    0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     ⋯     1     0    
[15,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     1    
[16,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[22,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[23,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0     0    
 [2,] 0     0     0     0     0     0     0     0    
 [3,] 0     0     0     0     0     0     0     0    
 [4,] 0     0     0     0     0     0     0     0    
 [5,] 0     0     0     0     0     0     0     0    
 [6,] 0     0     0     0     0     0     0     0    
 [7,] 0     0     0     0     0     0     0     0    
 [8,] 0     0     0     0     0     0     0     0    
 [9,] 0     0     0     0     0     0     0     0    
[10,] 0     0     0     0     0     0     0     0    
[11,] 0     0     0     0     0     0     0     0    
[12,] 0     0     0     0     0     0     0     0    
[13,] 0     0     0     0     0     0     0     0    
[14,] 0     0     0     0     0     0     0     0    
[15,] 0     0     0     0     0     0     0     0    
[16,] 1     0     0     0     0     0     0     0    
[17,] 0     1     0     0     0     0     0     0    
[18,] 0     0     1     0     0     0     0     0    
[19,] 0     0     0     1     0     0     0     0    
[20,] 0     0     0     0     1     0     0     0    
[21,] 0     0     0     0     0     1     0     0    
[22,] 0     0     0     0     0     0     1     0    
[23,] 0     0     0     0     0     0     0     1

In [8]:
V=I+U

In [9]:
Vi=I-W

In [10]:
Y<-matrix(c(2.3,1.8,2.8,1.5,2.2,3.8,1.8,3.7,1.7,2.8,2.8,2.2,3.2,1.9,1.8,3.5,2.8,2.1,3.4,3.2,3,3,5.9), nrow = 23)

In [11]:
Vi

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10] [,11] [,12] [,13]
 [1,] 1    0    0    0    0    0    0    0    0    0     ⋯     0     0    
 [2,] 0    1    0    0    0    0    0    0    0    0     ⋯     0     0    
 [3,] 0    0    1    0    0    0    0    0    0    0     ⋯     0     0    
 [4,] 0    0    0    1    0    0    0    0    0    0     ⋯     0     0    
 [5,] 0    0    0    0    1    0    0    0    0    0     ⋯     0     0    
 [6,] 0    0    0    0    0    1    0    0    0    0     ⋯     0     0    
 [7,] 0    0    0    0    0    0    1    0    0    0     ⋯     0     0    
 [8,] 0    0    0    0    0    0    0    1    0    0     ⋯     0     0    
 [9,] 0    0    0    0    0    0    0    0    1    0     ⋯     0     0    
[10,] 0    0    0    0    0    0    0    0    0    1     ⋯     0     0    
[11,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[12,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[13,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[14,] 0    0    0    0    0    0    0    0    0    0     ⋯     1     0    
[15,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     1    
[16,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[17,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[18,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[19,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[20,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[21,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[22,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
[23,] 0    0    0    0    0    0    0    0    0    0     ⋯     0     0    
      [,14] [,15] [,16] [,17] [,18] [,19] [,20] [,21]
 [1,] 0     0     0     0     0     0     0     0.00 
 [2,] 0     0     0     0     0     0     0     0.00 
 [3,] 0     0     0     0     0     0     0     0.00 
 [4,] 0     0     0     0     0     0     0     0.00 
 [5,] 0     0     0     0     0     0     0     0.00 
 [6,] 0     0     0     0     0     0     0     0.00 
 [7,] 0     0     0     0     0     0     0     0.00 
 [8,] 0     0     0     0     0     0     0     0.00 
 [9,] 0     0     0     0     0     0     0     0.00 
[10,] 0     0     0     0     0     0     0     0.00 
[11,] 0     0     0     0     0     0     0     0.00 
[12,] 0     0     0     0     0     0     0     0.00 
[13,] 0     0     0     0     0     0     0     0.00 
[14,] 0     0     0     0     0     0     0     0.00 
[15,] 0     0     0     0     0     0     0     0.00 
[16,] 1     0     0     0     0     0     0     0.00 
[17,] 0     1     0     0     0     0     0     0.00 
[18,] 0     0     1     0     0     0     0     0.00 
[19,] 0     0     0     1     0     0     0     0.00 
[20,] 0     0     0     0     1     0     0     0.00 
[21,] 0     0     0     0     0     1     0     0.00 
[22,] 0     0     0     0     0     0     1     0.00 
[23,] 0     0     0     0     0     0     0     0.04

In [12]:
Xt=t(X)

In [13]:
C=Xt%*%Vi%*%X

In [14]:
J=diag(1,nrow=2)

solve(C,J)

[,1]        [,2]       
[1,]  0.38593389 -0.08352231
[2,] -0.08352231  0.02048373

In [15]:
C1=solve(C,J)

In [16]:
C2=Xt%*%Vi%*%Y

In [17]:
C1

[,1]        [,2]       
[1,]  0.38593389 -0.08352231
[2,] -0.08352231  0.02048373

In [18]:
C1%*%C2

[,1]     
[1,] 1.8188667
[2,] 0.1941534

In [20]:
#H

In [21]:
X1<- c(1.76,1.55,2.73,2.73,2.56,2.8,2.8,1.84,2.16,1.98,0.59,0.8,0.8,1.05,1.8,1.8,1.77,2.3,2.03,1.91,1.91,1.91,0.76,2.13,2.13,1.51,2.05)

In [22]:
X1

[1] 1.76 1.55 2.73 2.73 2.56 2.80 2.80 1.84 2.16 1.98 0.59 0.80 0.80 1.05 1.80
[16] 1.80 1.77 2.30 2.03 1.91 1.91 1.91 0.76 2.13 2.13 1.51 2.05

In [23]:
X2<- c(0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.7,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.2,0.474,0.474,0.474,0.474,0.474,0.474,0.474,0.474,0.474)

In [24]:
X2

[1] 0.700 0.700 0.700 0.700 0.700 0.700 0.700 0.700 0.700 0.200 0.200 0.200
[13] 0.200 0.200 0.200 0.200 0.200 0.200 0.474 0.474 0.474 0.474 0.474 0.474
[25] 0.474 0.474 0.474

In [25]:
X3<- c(7.8,8.9,8.9,7.2,8.4,8.7,7.4,8.7,8.8,7.6,6.5,6.7,6.2,7,7.3,6.5,7.6,8.2,7.6,8.3,8.2,6.9,7.4,7.6,6.9,7.5,7.6)

In [26]:
X3

[1] 7.8 8.9 8.9 7.2 8.4 8.7 7.4 8.7 8.8 7.6 6.5 6.7 6.2 7.0 7.3 6.5 7.6 8.2 7.6
[20] 8.3 8.2 6.9 7.4 7.6 6.9 7.5 7.6

In [27]:
Yh<- c(110.4,102.8,101,108.4,100.7,100.3,102,93.7,98.9,96.6,99.4,96.2,99,88.4,75.3,92,82.4,77.1,74,65.7,56.8,62.1,61,53.2,59.4,58.7,58)

In [28]:
Yh

[1] 110.4 102.8 101.0 108.4 100.7 100.3 102.0  93.7  98.9  96.6  99.4  96.2
[13]  99.0  88.4  75.3  92.0  82.4  77.1  74.0  65.7  56.8  62.1  61.0  53.2
[25]  59.4  58.7  58.0